// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:whatsapp/pass.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:218537554845:web:fac41e0c80ebed9504f574',
    messagingSenderId: '218537554845',
    projectId: 'whatsappui-4528c',
    authDomain: 'whatsappui-4528c.firebaseapp.com',
    storageBucket: 'whatsappui-4528c.firebasestorage.app',
    measurementId: 'G-7GXTQ1NZ13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCNQMldWI3dtzYTVcZdzm4NW06HKYpGj0',
    appId: '1:218537554845:android:11ca1702622d41bd04f574',
    messagingSenderId: '218537554845',
    projectId: 'whatsappui-4528c',
    storageBucket: 'whatsappui-4528c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvsMe9HoOotUelDg35AysAgh8fla3zC1o',
    appId: '1:218537554845:ios:09269e01d67dab1404f574',
    messagingSenderId: '218537554845',
    projectId: 'whatsappui-4528c',
    storageBucket: 'whatsappui-4528c.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvsMe9HoOotUelDg35AysAgh8fla3zC1o',
    appId: '1:218537554845:ios:09269e01d67dab1404f574',
    messagingSenderId: '218537554845',
    projectId: 'whatsappui-4528c',
    storageBucket: 'whatsappui-4528c.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9iv9B8mmgpytdawGoGBTMz5S5MtTuzSk',
    appId: '1:218537554845:web:ab2fa3f1bee33d8504f574',
    messagingSenderId: '218537554845',
    projectId: 'whatsappui-4528c',
    authDomain: 'whatsappui-4528c.firebaseapp.com',
    storageBucket: 'whatsappui-4528c.firebasestorage.app',
    measurementId: 'G-5N33NZKR4H',
  );
}
